# Actions possibles
ACTION_CREATE = "CREATE"
ACTION_READ   = "READ"
ACTION_WRITE  = "WRITE"
ACTION_DELETE = "DELETE"
ACTION_LOCK   = "LOCK"
ACTION_UNLOCK = "UNLOCK"
ACTION_LIST = "LIST"

STATUS_OK = 200

STATUS_ERROR_FILE_LOCKED = 401
STATUS_ERROR_FILE_NOT_FOUND = 404
STATUS_ERROR_UNKNOWN = 400